### ISSUE TITLE
Enveronment variable in CUDA

### ISSUE THREAD

**Issue by xumi1993** [ranoriginals/ranoriginals.github.io#2]
Thanks for sharing the configurations, but the definition of the enveronment variable of CUDA doesn't meet the specifications.
You defined the variable of `CUDA_HOME`, but did not call it in following lines. The same issue was appeared on a definition of the PGI. Better codes as follows:

```Bash
export CUDA_HOME=/usr/local/cuda-10.0 
export PATH=$CUDA_HOME/bin:$PATH 
export LD_LIBRARY_PATH=$CUDA_HOME/lib64:$LD_LIBRARY_PATH 
export LIBRARY_PATH=$CUDA_HOME/lib64:$LIBRARY_PATH 
```

**Comment by ranoriginals** [comment]
OK, I have modified the blog. Thank you for your suggestion!
